#PGI_HDF5_BIN=/project/fchen14/packages/hdf5-1.10.4/install/bin

#PGI_H5CC=$(PGI_HDF5_BIN)/h5pcc
PGI_H5CC=h5pcc
#CFLAGS_PGI_OMP=-O3 -std=gnu99 -fopenmp
CFLAGS_PGI_OMP=-O3 -fopenmp

#PCB_MPI_SRC=src/c/ph5ex.c
PCB_MPI_SRC=src/c/ph5_cmb_blks.c

mpichomp: $(PCB_MPI_SRC)
	$(PGI_H5CC) $(CFLAGS_PGI_OMP) $(PCB_MPI_SRC) -o $@.out

all: $(BIN)

clean:
	rm -rf pgi.mpi.omp.out pgi.mpi.acc.out
